// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protobuf/message.proto

package protobuf

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import strconv "strconv"

import bytes "bytes"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RoutingType int32

const (
	DIRECT    RoutingType = 0
	RELAY     RoutingType = 1
	BROADCAST RoutingType = 2
)

var RoutingType_name = map[int32]string{
	0: "DIRECT",
	1: "RELAY",
	2: "BROADCAST",
}
var RoutingType_value = map[string]int32{
	"DIRECT":    0,
	"RELAY":     1,
	"BROADCAST": 2,
}

func (RoutingType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_478bd8fc7639d004, []int{0}
}

type MessageType int32

const (
	PING              MessageType = 0
	GET_NODE          MessageType = 1
	GET_SUCC_AND_PRED MessageType = 2
	FIND_SUCCESSORS   MessageType = 3
	FIND_PREDECESSOR  MessageType = 4
)

var MessageType_name = map[int32]string{
	0: "PING",
	1: "GET_NODE",
	2: "GET_SUCC_AND_PRED",
	3: "FIND_SUCCESSORS",
	4: "FIND_PREDECESSOR",
}
var MessageType_value = map[string]int32{
	"PING":              0,
	"GET_NODE":          1,
	"GET_SUCC_AND_PRED": 2,
	"FIND_SUCCESSORS":   3,
	"FIND_PREDECESSOR":  4,
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_478bd8fc7639d004, []int{1}
}

type Message struct {
	RoutingType RoutingType `protobuf:"varint,1,opt,name=routing_type,json=routingType,proto3,enum=protobuf.RoutingType" json:"routing_type,omitempty"`
	MessageType MessageType `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,enum=protobuf.MessageType" json:"message_type,omitempty"`
	Message     []byte      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	MessageId   []byte      `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ReplyToId   []byte      `protobuf:"bytes,5,opt,name=reply_to_id,json=replyToId,proto3" json:"reply_to_id,omitempty"`
	SrcId       []byte      `protobuf:"bytes,6,opt,name=src_id,json=srcId,proto3" json:"src_id,omitempty"`
	DestId      []byte      `protobuf:"bytes,7,opt,name=dest_id,json=destId,proto3" json:"dest_id,omitempty"`
}

func (m *Message) Reset()      { *m = Message{} }
func (*Message) ProtoMessage() {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_478bd8fc7639d004, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Message.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return m.Size()
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetRoutingType() RoutingType {
	if m != nil {
		return m.RoutingType
	}
	return DIRECT
}

func (m *Message) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return PING
}

func (m *Message) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Message) GetMessageId() []byte {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *Message) GetReplyToId() []byte {
	if m != nil {
		return m.ReplyToId
	}
	return nil
}

func (m *Message) GetSrcId() []byte {
	if m != nil {
		return m.SrcId
	}
	return nil
}

func (m *Message) GetDestId() []byte {
	if m != nil {
		return m.DestId
	}
	return nil
}

type Ping struct {
}

func (m *Ping) Reset()      { *m = Ping{} }
func (*Ping) ProtoMessage() {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_478bd8fc7639d004, []int{1}
}
func (m *Ping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(dst, src)
}
func (m *Ping) XXX_Size() int {
	return m.Size()
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Pong struct {
}

func (m *Pong) Reset()      { *m = Pong{} }
func (*Pong) ProtoMessage() {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_478bd8fc7639d004, []int{2}
}
func (m *Pong) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(dst, src)
}
func (m *Pong) XXX_Size() int {
	return m.Size()
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

type GetNode struct {
}

func (m *GetNode) Reset()      { *m = GetNode{} }
func (*GetNode) ProtoMessage() {}
func (*GetNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_478bd8fc7639d004, []int{3}
}
func (m *GetNode) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetNode.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *GetNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNode.Merge(dst, src)
}
func (m *GetNode) XXX_Size() int {
	return m.Size()
}
func (m *GetNode) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNode.DiscardUnknown(m)
}

var xxx_messageInfo_GetNode proto.InternalMessageInfo

type GetNodeReply struct {
	Node *Node `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
}

func (m *GetNodeReply) Reset()      { *m = GetNodeReply{} }
func (*GetNodeReply) ProtoMessage() {}
func (*GetNodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_478bd8fc7639d004, []int{4}
}
func (m *GetNodeReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetNodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetNodeReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *GetNodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeReply.Merge(dst, src)
}
func (m *GetNodeReply) XXX_Size() int {
	return m.Size()
}
func (m *GetNodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeReply proto.InternalMessageInfo

func (m *GetNodeReply) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type GetSuccAndPred struct {
	NumSucc uint32 `protobuf:"varint,1,opt,name=num_succ,json=numSucc,proto3" json:"num_succ,omitempty"`
	NumPred uint32 `protobuf:"varint,2,opt,name=num_pred,json=numPred,proto3" json:"num_pred,omitempty"`
}

func (m *GetSuccAndPred) Reset()      { *m = GetSuccAndPred{} }
func (*GetSuccAndPred) ProtoMessage() {}
func (*GetSuccAndPred) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_478bd8fc7639d004, []int{5}
}
func (m *GetSuccAndPred) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetSuccAndPred) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetSuccAndPred.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *GetSuccAndPred) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSuccAndPred.Merge(dst, src)
}
func (m *GetSuccAndPred) XXX_Size() int {
	return m.Size()
}
func (m *GetSuccAndPred) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSuccAndPred.DiscardUnknown(m)
}

var xxx_messageInfo_GetSuccAndPred proto.InternalMessageInfo

func (m *GetSuccAndPred) GetNumSucc() uint32 {
	if m != nil {
		return m.NumSucc
	}
	return 0
}

func (m *GetSuccAndPred) GetNumPred() uint32 {
	if m != nil {
		return m.NumPred
	}
	return 0
}

type GetSuccAndPredReply struct {
	Successors   []*Node `protobuf:"bytes,1,rep,name=successors" json:"successors,omitempty"`
	Predecessors []*Node `protobuf:"bytes,2,rep,name=predecessors" json:"predecessors,omitempty"`
}

func (m *GetSuccAndPredReply) Reset()      { *m = GetSuccAndPredReply{} }
func (*GetSuccAndPredReply) ProtoMessage() {}
func (*GetSuccAndPredReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_478bd8fc7639d004, []int{6}
}
func (m *GetSuccAndPredReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetSuccAndPredReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetSuccAndPredReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *GetSuccAndPredReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSuccAndPredReply.Merge(dst, src)
}
func (m *GetSuccAndPredReply) XXX_Size() int {
	return m.Size()
}
func (m *GetSuccAndPredReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSuccAndPredReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetSuccAndPredReply proto.InternalMessageInfo

func (m *GetSuccAndPredReply) GetSuccessors() []*Node {
	if m != nil {
		return m.Successors
	}
	return nil
}

func (m *GetSuccAndPredReply) GetPredecessors() []*Node {
	if m != nil {
		return m.Predecessors
	}
	return nil
}

type FindSuccessors struct {
	Key     []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	NumSucc uint32 `protobuf:"varint,2,opt,name=num_succ,json=numSucc,proto3" json:"num_succ,omitempty"`
}

func (m *FindSuccessors) Reset()      { *m = FindSuccessors{} }
func (*FindSuccessors) ProtoMessage() {}
func (*FindSuccessors) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_478bd8fc7639d004, []int{7}
}
func (m *FindSuccessors) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FindSuccessors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FindSuccessors.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *FindSuccessors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindSuccessors.Merge(dst, src)
}
func (m *FindSuccessors) XXX_Size() int {
	return m.Size()
}
func (m *FindSuccessors) XXX_DiscardUnknown() {
	xxx_messageInfo_FindSuccessors.DiscardUnknown(m)
}

var xxx_messageInfo_FindSuccessors proto.InternalMessageInfo

func (m *FindSuccessors) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *FindSuccessors) GetNumSucc() uint32 {
	if m != nil {
		return m.NumSucc
	}
	return 0
}

type FindSuccessorsReply struct {
	Successors []*Node `protobuf:"bytes,1,rep,name=successors" json:"successors,omitempty"`
}

func (m *FindSuccessorsReply) Reset()      { *m = FindSuccessorsReply{} }
func (*FindSuccessorsReply) ProtoMessage() {}
func (*FindSuccessorsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_478bd8fc7639d004, []int{8}
}
func (m *FindSuccessorsReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FindSuccessorsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FindSuccessorsReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *FindSuccessorsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindSuccessorsReply.Merge(dst, src)
}
func (m *FindSuccessorsReply) XXX_Size() int {
	return m.Size()
}
func (m *FindSuccessorsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FindSuccessorsReply.DiscardUnknown(m)
}

var xxx_messageInfo_FindSuccessorsReply proto.InternalMessageInfo

func (m *FindSuccessorsReply) GetSuccessors() []*Node {
	if m != nil {
		return m.Successors
	}
	return nil
}

type FindPredecessor struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *FindPredecessor) Reset()      { *m = FindPredecessor{} }
func (*FindPredecessor) ProtoMessage() {}
func (*FindPredecessor) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_478bd8fc7639d004, []int{9}
}
func (m *FindPredecessor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FindPredecessor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FindPredecessor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *FindPredecessor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindPredecessor.Merge(dst, src)
}
func (m *FindPredecessor) XXX_Size() int {
	return m.Size()
}
func (m *FindPredecessor) XXX_DiscardUnknown() {
	xxx_messageInfo_FindPredecessor.DiscardUnknown(m)
}

var xxx_messageInfo_FindPredecessor proto.InternalMessageInfo

func (m *FindPredecessor) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type FindPredecessorReply struct {
	Predecessor *Node `protobuf:"bytes,1,opt,name=predecessor" json:"predecessor,omitempty"`
}

func (m *FindPredecessorReply) Reset()      { *m = FindPredecessorReply{} }
func (*FindPredecessorReply) ProtoMessage() {}
func (*FindPredecessorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_478bd8fc7639d004, []int{10}
}
func (m *FindPredecessorReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FindPredecessorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FindPredecessorReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *FindPredecessorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindPredecessorReply.Merge(dst, src)
}
func (m *FindPredecessorReply) XXX_Size() int {
	return m.Size()
}
func (m *FindPredecessorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FindPredecessorReply.DiscardUnknown(m)
}

var xxx_messageInfo_FindPredecessorReply proto.InternalMessageInfo

func (m *FindPredecessorReply) GetPredecessor() *Node {
	if m != nil {
		return m.Predecessor
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "protobuf.Message")
	proto.RegisterType((*Ping)(nil), "protobuf.Ping")
	proto.RegisterType((*Pong)(nil), "protobuf.Pong")
	proto.RegisterType((*GetNode)(nil), "protobuf.GetNode")
	proto.RegisterType((*GetNodeReply)(nil), "protobuf.GetNodeReply")
	proto.RegisterType((*GetSuccAndPred)(nil), "protobuf.GetSuccAndPred")
	proto.RegisterType((*GetSuccAndPredReply)(nil), "protobuf.GetSuccAndPredReply")
	proto.RegisterType((*FindSuccessors)(nil), "protobuf.FindSuccessors")
	proto.RegisterType((*FindSuccessorsReply)(nil), "protobuf.FindSuccessorsReply")
	proto.RegisterType((*FindPredecessor)(nil), "protobuf.FindPredecessor")
	proto.RegisterType((*FindPredecessorReply)(nil), "protobuf.FindPredecessorReply")
	proto.RegisterEnum("protobuf.RoutingType", RoutingType_name, RoutingType_value)
	proto.RegisterEnum("protobuf.MessageType", MessageType_name, MessageType_value)
}
func (x RoutingType) String() string {
	s, ok := RoutingType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x MessageType) String() string {
	s, ok := MessageType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *Message) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message)
	if !ok {
		that2, ok := that.(Message)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.RoutingType != that1.RoutingType {
		return false
	}
	if this.MessageType != that1.MessageType {
		return false
	}
	if !bytes.Equal(this.Message, that1.Message) {
		return false
	}
	if !bytes.Equal(this.MessageId, that1.MessageId) {
		return false
	}
	if !bytes.Equal(this.ReplyToId, that1.ReplyToId) {
		return false
	}
	if !bytes.Equal(this.SrcId, that1.SrcId) {
		return false
	}
	if !bytes.Equal(this.DestId, that1.DestId) {
		return false
	}
	return true
}
func (this *Ping) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Ping)
	if !ok {
		that2, ok := that.(Ping)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *Pong) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Pong)
	if !ok {
		that2, ok := that.(Pong)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *GetNode) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetNode)
	if !ok {
		that2, ok := that.(GetNode)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *GetNodeReply) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetNodeReply)
	if !ok {
		that2, ok := that.(GetNodeReply)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Node.Equal(that1.Node) {
		return false
	}
	return true
}
func (this *GetSuccAndPred) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetSuccAndPred)
	if !ok {
		that2, ok := that.(GetSuccAndPred)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.NumSucc != that1.NumSucc {
		return false
	}
	if this.NumPred != that1.NumPred {
		return false
	}
	return true
}
func (this *GetSuccAndPredReply) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetSuccAndPredReply)
	if !ok {
		that2, ok := that.(GetSuccAndPredReply)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Successors) != len(that1.Successors) {
		return false
	}
	for i := range this.Successors {
		if !this.Successors[i].Equal(that1.Successors[i]) {
			return false
		}
	}
	if len(this.Predecessors) != len(that1.Predecessors) {
		return false
	}
	for i := range this.Predecessors {
		if !this.Predecessors[i].Equal(that1.Predecessors[i]) {
			return false
		}
	}
	return true
}
func (this *FindSuccessors) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FindSuccessors)
	if !ok {
		that2, ok := that.(FindSuccessors)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Key, that1.Key) {
		return false
	}
	if this.NumSucc != that1.NumSucc {
		return false
	}
	return true
}
func (this *FindSuccessorsReply) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FindSuccessorsReply)
	if !ok {
		that2, ok := that.(FindSuccessorsReply)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Successors) != len(that1.Successors) {
		return false
	}
	for i := range this.Successors {
		if !this.Successors[i].Equal(that1.Successors[i]) {
			return false
		}
	}
	return true
}
func (this *FindPredecessor) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FindPredecessor)
	if !ok {
		that2, ok := that.(FindPredecessor)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Key, that1.Key) {
		return false
	}
	return true
}
func (this *FindPredecessorReply) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FindPredecessorReply)
	if !ok {
		that2, ok := that.(FindPredecessorReply)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Predecessor.Equal(that1.Predecessor) {
		return false
	}
	return true
}
func (this *Message) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&protobuf.Message{")
	s = append(s, "RoutingType: "+fmt.Sprintf("%#v", this.RoutingType)+",\n")
	s = append(s, "MessageType: "+fmt.Sprintf("%#v", this.MessageType)+",\n")
	s = append(s, "Message: "+fmt.Sprintf("%#v", this.Message)+",\n")
	s = append(s, "MessageId: "+fmt.Sprintf("%#v", this.MessageId)+",\n")
	s = append(s, "ReplyToId: "+fmt.Sprintf("%#v", this.ReplyToId)+",\n")
	s = append(s, "SrcId: "+fmt.Sprintf("%#v", this.SrcId)+",\n")
	s = append(s, "DestId: "+fmt.Sprintf("%#v", this.DestId)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Ping) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&protobuf.Ping{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Pong) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&protobuf.Pong{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetNode) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&protobuf.GetNode{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetNodeReply) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&protobuf.GetNodeReply{")
	if this.Node != nil {
		s = append(s, "Node: "+fmt.Sprintf("%#v", this.Node)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetSuccAndPred) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&protobuf.GetSuccAndPred{")
	s = append(s, "NumSucc: "+fmt.Sprintf("%#v", this.NumSucc)+",\n")
	s = append(s, "NumPred: "+fmt.Sprintf("%#v", this.NumPred)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetSuccAndPredReply) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&protobuf.GetSuccAndPredReply{")
	if this.Successors != nil {
		s = append(s, "Successors: "+fmt.Sprintf("%#v", this.Successors)+",\n")
	}
	if this.Predecessors != nil {
		s = append(s, "Predecessors: "+fmt.Sprintf("%#v", this.Predecessors)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *FindSuccessors) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&protobuf.FindSuccessors{")
	s = append(s, "Key: "+fmt.Sprintf("%#v", this.Key)+",\n")
	s = append(s, "NumSucc: "+fmt.Sprintf("%#v", this.NumSucc)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *FindSuccessorsReply) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&protobuf.FindSuccessorsReply{")
	if this.Successors != nil {
		s = append(s, "Successors: "+fmt.Sprintf("%#v", this.Successors)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *FindPredecessor) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&protobuf.FindPredecessor{")
	s = append(s, "Key: "+fmt.Sprintf("%#v", this.Key)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *FindPredecessorReply) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&protobuf.FindPredecessorReply{")
	if this.Predecessor != nil {
		s = append(s, "Predecessor: "+fmt.Sprintf("%#v", this.Predecessor)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringMessage(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.RoutingType != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.RoutingType))
	}
	if m.MessageType != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.MessageType))
	}
	if len(m.Message) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.Message)))
		i += copy(dAtA[i:], m.Message)
	}
	if len(m.MessageId) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.MessageId)))
		i += copy(dAtA[i:], m.MessageId)
	}
	if len(m.ReplyToId) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.ReplyToId)))
		i += copy(dAtA[i:], m.ReplyToId)
	}
	if len(m.SrcId) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.SrcId)))
		i += copy(dAtA[i:], m.SrcId)
	}
	if len(m.DestId) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.DestId)))
		i += copy(dAtA[i:], m.DestId)
	}
	return i, nil
}

func (m *Ping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ping) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *Pong) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Pong) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *GetNode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetNode) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *GetNodeReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetNodeReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Node != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Node.Size()))
		n1, err := m.Node.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func (m *GetSuccAndPred) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetSuccAndPred) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.NumSucc != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.NumSucc))
	}
	if m.NumPred != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.NumPred))
	}
	return i, nil
}

func (m *GetSuccAndPredReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetSuccAndPredReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Successors) > 0 {
		for _, msg := range m.Successors {
			dAtA[i] = 0xa
			i++
			i = encodeVarintMessage(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Predecessors) > 0 {
		for _, msg := range m.Predecessors {
			dAtA[i] = 0x12
			i++
			i = encodeVarintMessage(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *FindSuccessors) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FindSuccessors) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Key) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.Key)))
		i += copy(dAtA[i:], m.Key)
	}
	if m.NumSucc != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.NumSucc))
	}
	return i, nil
}

func (m *FindSuccessorsReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FindSuccessorsReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Successors) > 0 {
		for _, msg := range m.Successors {
			dAtA[i] = 0xa
			i++
			i = encodeVarintMessage(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *FindPredecessor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FindPredecessor) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Key) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.Key)))
		i += copy(dAtA[i:], m.Key)
	}
	return i, nil
}

func (m *FindPredecessorReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FindPredecessorReply) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Predecessor != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Predecessor.Size()))
		n2, err := m.Predecessor.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	return i, nil
}

func encodeVarintMessage(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func NewPopulatedMessage(r randyMessage, easy bool) *Message {
	this := &Message{}
	this.RoutingType = RoutingType([]int32{0, 1, 2}[r.Intn(3)])
	this.MessageType = MessageType([]int32{0, 1, 2, 3, 4}[r.Intn(5)])
	v1 := r.Intn(100)
	this.Message = make([]byte, v1)
	for i := 0; i < v1; i++ {
		this.Message[i] = byte(r.Intn(256))
	}
	v2 := r.Intn(100)
	this.MessageId = make([]byte, v2)
	for i := 0; i < v2; i++ {
		this.MessageId[i] = byte(r.Intn(256))
	}
	v3 := r.Intn(100)
	this.ReplyToId = make([]byte, v3)
	for i := 0; i < v3; i++ {
		this.ReplyToId[i] = byte(r.Intn(256))
	}
	v4 := r.Intn(100)
	this.SrcId = make([]byte, v4)
	for i := 0; i < v4; i++ {
		this.SrcId[i] = byte(r.Intn(256))
	}
	v5 := r.Intn(100)
	this.DestId = make([]byte, v5)
	for i := 0; i < v5; i++ {
		this.DestId[i] = byte(r.Intn(256))
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedPing(r randyMessage, easy bool) *Ping {
	this := &Ping{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedPong(r randyMessage, easy bool) *Pong {
	this := &Pong{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetNode(r randyMessage, easy bool) *GetNode {
	this := &GetNode{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetNodeReply(r randyMessage, easy bool) *GetNodeReply {
	this := &GetNodeReply{}
	if r.Intn(10) != 0 {
		this.Node = NewPopulatedNode(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetSuccAndPred(r randyMessage, easy bool) *GetSuccAndPred {
	this := &GetSuccAndPred{}
	this.NumSucc = uint32(r.Uint32())
	this.NumPred = uint32(r.Uint32())
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedGetSuccAndPredReply(r randyMessage, easy bool) *GetSuccAndPredReply {
	this := &GetSuccAndPredReply{}
	if r.Intn(10) != 0 {
		v6 := r.Intn(5)
		this.Successors = make([]*Node, v6)
		for i := 0; i < v6; i++ {
			this.Successors[i] = NewPopulatedNode(r, easy)
		}
	}
	if r.Intn(10) != 0 {
		v7 := r.Intn(5)
		this.Predecessors = make([]*Node, v7)
		for i := 0; i < v7; i++ {
			this.Predecessors[i] = NewPopulatedNode(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedFindSuccessors(r randyMessage, easy bool) *FindSuccessors {
	this := &FindSuccessors{}
	v8 := r.Intn(100)
	this.Key = make([]byte, v8)
	for i := 0; i < v8; i++ {
		this.Key[i] = byte(r.Intn(256))
	}
	this.NumSucc = uint32(r.Uint32())
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedFindSuccessorsReply(r randyMessage, easy bool) *FindSuccessorsReply {
	this := &FindSuccessorsReply{}
	if r.Intn(10) != 0 {
		v9 := r.Intn(5)
		this.Successors = make([]*Node, v9)
		for i := 0; i < v9; i++ {
			this.Successors[i] = NewPopulatedNode(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedFindPredecessor(r randyMessage, easy bool) *FindPredecessor {
	this := &FindPredecessor{}
	v10 := r.Intn(100)
	this.Key = make([]byte, v10)
	for i := 0; i < v10; i++ {
		this.Key[i] = byte(r.Intn(256))
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedFindPredecessorReply(r randyMessage, easy bool) *FindPredecessorReply {
	this := &FindPredecessorReply{}
	if r.Intn(10) != 0 {
		this.Predecessor = NewPopulatedNode(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyMessage interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneMessage(r randyMessage) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringMessage(r randyMessage) string {
	v11 := r.Intn(100)
	tmps := make([]rune, v11)
	for i := 0; i < v11; i++ {
		tmps[i] = randUTF8RuneMessage(r)
	}
	return string(tmps)
}
func randUnrecognizedMessage(r randyMessage, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldMessage(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldMessage(dAtA []byte, r randyMessage, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateMessage(dAtA, uint64(key))
		v12 := r.Int63()
		if r.Intn(2) == 0 {
			v12 *= -1
		}
		dAtA = encodeVarintPopulateMessage(dAtA, uint64(v12))
	case 1:
		dAtA = encodeVarintPopulateMessage(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateMessage(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateMessage(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateMessage(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateMessage(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RoutingType != 0 {
		n += 1 + sovMessage(uint64(m.RoutingType))
	}
	if m.MessageType != 0 {
		n += 1 + sovMessage(uint64(m.MessageType))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.MessageId)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.ReplyToId)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.SrcId)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.DestId)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *Ping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Pong) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetNode) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetNodeReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Node != nil {
		l = m.Node.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *GetSuccAndPred) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NumSucc != 0 {
		n += 1 + sovMessage(uint64(m.NumSucc))
	}
	if m.NumPred != 0 {
		n += 1 + sovMessage(uint64(m.NumPred))
	}
	return n
}

func (m *GetSuccAndPredReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Successors) > 0 {
		for _, e := range m.Successors {
			l = e.Size()
			n += 1 + l + sovMessage(uint64(l))
		}
	}
	if len(m.Predecessors) > 0 {
		for _, e := range m.Predecessors {
			l = e.Size()
			n += 1 + l + sovMessage(uint64(l))
		}
	}
	return n
}

func (m *FindSuccessors) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.NumSucc != 0 {
		n += 1 + sovMessage(uint64(m.NumSucc))
	}
	return n
}

func (m *FindSuccessorsReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Successors) > 0 {
		for _, e := range m.Successors {
			l = e.Size()
			n += 1 + l + sovMessage(uint64(l))
		}
	}
	return n
}

func (m *FindPredecessor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *FindPredecessorReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Predecessor != nil {
		l = m.Predecessor.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func sovMessage(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMessage(x uint64) (n int) {
	return sovMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Message) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Message{`,
		`RoutingType:` + fmt.Sprintf("%v", this.RoutingType) + `,`,
		`MessageType:` + fmt.Sprintf("%v", this.MessageType) + `,`,
		`Message:` + fmt.Sprintf("%v", this.Message) + `,`,
		`MessageId:` + fmt.Sprintf("%v", this.MessageId) + `,`,
		`ReplyToId:` + fmt.Sprintf("%v", this.ReplyToId) + `,`,
		`SrcId:` + fmt.Sprintf("%v", this.SrcId) + `,`,
		`DestId:` + fmt.Sprintf("%v", this.DestId) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Ping) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Ping{`,
		`}`,
	}, "")
	return s
}
func (this *Pong) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Pong{`,
		`}`,
	}, "")
	return s
}
func (this *GetNode) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetNode{`,
		`}`,
	}, "")
	return s
}
func (this *GetNodeReply) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetNodeReply{`,
		`Node:` + strings.Replace(fmt.Sprintf("%v", this.Node), "Node", "Node", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetSuccAndPred) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetSuccAndPred{`,
		`NumSucc:` + fmt.Sprintf("%v", this.NumSucc) + `,`,
		`NumPred:` + fmt.Sprintf("%v", this.NumPred) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetSuccAndPredReply) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetSuccAndPredReply{`,
		`Successors:` + strings.Replace(fmt.Sprintf("%v", this.Successors), "Node", "Node", 1) + `,`,
		`Predecessors:` + strings.Replace(fmt.Sprintf("%v", this.Predecessors), "Node", "Node", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FindSuccessors) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FindSuccessors{`,
		`Key:` + fmt.Sprintf("%v", this.Key) + `,`,
		`NumSucc:` + fmt.Sprintf("%v", this.NumSucc) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FindSuccessorsReply) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FindSuccessorsReply{`,
		`Successors:` + strings.Replace(fmt.Sprintf("%v", this.Successors), "Node", "Node", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FindPredecessor) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FindPredecessor{`,
		`Key:` + fmt.Sprintf("%v", this.Key) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FindPredecessorReply) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FindPredecessorReply{`,
		`Predecessor:` + strings.Replace(fmt.Sprintf("%v", this.Predecessor), "Node", "Node", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringMessage(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoutingType", wireType)
			}
			m.RoutingType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RoutingType |= (RoutingType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageType", wireType)
			}
			m.MessageType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageType |= (MessageType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = append(m.Message[:0], dAtA[iNdEx:postIndex]...)
			if m.Message == nil {
				m.Message = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageId = append(m.MessageId[:0], dAtA[iNdEx:postIndex]...)
			if m.MessageId == nil {
				m.MessageId = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplyToId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReplyToId = append(m.ReplyToId[:0], dAtA[iNdEx:postIndex]...)
			if m.ReplyToId == nil {
				m.ReplyToId = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SrcId = append(m.SrcId[:0], dAtA[iNdEx:postIndex]...)
			if m.SrcId == nil {
				m.SrcId = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestId = append(m.DestId[:0], dAtA[iNdEx:postIndex]...)
			if m.DestId == nil {
				m.DestId = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Pong) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Pong: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Pong: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetNode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetNode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetNode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetNodeReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetNodeReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetNodeReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Node", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Node == nil {
				m.Node = &Node{}
			}
			if err := m.Node.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetSuccAndPred) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetSuccAndPred: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetSuccAndPred: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumSucc", wireType)
			}
			m.NumSucc = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumSucc |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumPred", wireType)
			}
			m.NumPred = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumPred |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetSuccAndPredReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetSuccAndPredReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetSuccAndPredReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Successors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Successors = append(m.Successors, &Node{})
			if err := m.Successors[len(m.Successors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Predecessors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Predecessors = append(m.Predecessors, &Node{})
			if err := m.Predecessors[len(m.Predecessors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FindSuccessors) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FindSuccessors: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FindSuccessors: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumSucc", wireType)
			}
			m.NumSucc = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumSucc |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FindSuccessorsReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FindSuccessorsReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FindSuccessorsReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Successors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Successors = append(m.Successors, &Node{})
			if err := m.Successors[len(m.Successors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FindPredecessor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FindPredecessor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FindPredecessor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FindPredecessorReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FindPredecessorReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FindPredecessorReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Predecessor", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Predecessor == nil {
				m.Predecessor = &Node{}
			}
			if err := m.Predecessor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMessage
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMessage
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMessage(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMessage = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessage   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("protobuf/message.proto", fileDescriptor_message_478bd8fc7639d004) }

var fileDescriptor_message_478bd8fc7639d004 = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x3f, 0x6f, 0xd3, 0x40,
	0x1c, 0xf5, 0x25, 0x69, 0xfe, 0xfc, 0x92, 0xa6, 0xe6, 0xd2, 0x42, 0xa8, 0xc4, 0xa9, 0x32, 0x4b,
	0x55, 0x89, 0x14, 0xa5, 0x0b, 0x03, 0x0c, 0x69, 0xec, 0x06, 0x4b, 0x90, 0x46, 0x76, 0x18, 0x98,
	0x2c, 0xea, 0x3b, 0x4c, 0x04, 0xf1, 0x45, 0xfe, 0x33, 0x64, 0x63, 0x62, 0xe6, 0x63, 0xf0, 0x11,
	0xf8, 0x08, 0x8c, 0x1d, 0x3b, 0x12, 0x67, 0x61, 0xec, 0xc8, 0x88, 0xee, 0x6c, 0x37, 0x49, 0x29,
	0x0b, 0x53, 0xee, 0xbd, 0xf7, 0x7b, 0xcf, 0xef, 0x77, 0x39, 0xb8, 0x3f, 0x0b, 0x78, 0xc4, 0x2f,
	0xe2, 0xf7, 0xc7, 0x53, 0x16, 0x86, 0xef, 0x3c, 0xd6, 0x91, 0x04, 0xae, 0xe6, 0xfc, 0xfe, 0x13,
	0x6f, 0x12, 0x7d, 0x88, 0x2f, 0x3a, 0x2e, 0x9f, 0x1e, 0x7b, 0xdc, 0xe3, 0xc7, 0x37, 0x0e, 0x81,
	0x24, 0x90, 0xa7, 0xd4, 0xb8, 0xdf, 0xba, 0x91, 0x7d, 0x4e, 0xb3, 0x34, 0xed, 0x4b, 0x01, 0x2a,
	0xaf, 0xd3, 0x7c, 0xfc, 0x0c, 0x1a, 0x01, 0x8f, 0xa3, 0x89, 0xef, 0x39, 0xd1, 0x7c, 0xc6, 0xda,
	0xe8, 0x00, 0x1d, 0x36, 0xbb, 0x7b, 0x9d, 0xdc, 0xd7, 0xb1, 0x52, 0x75, 0x3c, 0x9f, 0x31, 0xab,
	0x1e, 0xac, 0x80, 0x70, 0x66, 0x25, 0x53, 0x67, 0xe1, 0xb6, 0x33, 0xfb, 0x44, 0xea, 0x9c, 0xae,
	0x00, 0x6e, 0x43, 0x25, 0x83, 0xed, 0xe2, 0x01, 0x3a, 0x6c, 0x58, 0x39, 0xc4, 0x8f, 0x00, 0xf2,
	0xcc, 0x09, 0x6d, 0x97, 0xa4, 0x58, 0xcb, 0x18, 0x93, 0x62, 0x02, 0xf5, 0x80, 0xcd, 0x3e, 0xcd,
	0x9d, 0x88, 0x0b, 0x7d, 0x2b, 0xd5, 0x25, 0x35, 0xe6, 0x26, 0xc5, 0x7b, 0x50, 0x0e, 0x03, 0x57,
	0x48, 0x65, 0x29, 0x6d, 0x85, 0x81, 0x6b, 0x52, 0xfc, 0x00, 0x2a, 0x94, 0x85, 0x91, 0xe0, 0x2b,
	0x92, 0x2f, 0x0b, 0x68, 0x52, 0xad, 0x0c, 0xa5, 0xd1, 0xc4, 0xf7, 0xe4, 0x2f, 0xf7, 0x3d, 0xad,
	0x06, 0x95, 0x01, 0x8b, 0x86, 0x9c, 0x32, 0xad, 0x0b, 0x8d, 0xec, 0x68, 0x89, 0x78, 0xac, 0x41,
	0x49, 0xdc, 0xa0, 0xbc, 0x9f, 0x7a, 0xb7, 0xb9, 0xda, 0x52, 0x8e, 0x48, 0x4d, 0x3b, 0x83, 0xe6,
	0x80, 0x45, 0x76, 0xec, 0xba, 0x3d, 0x9f, 0x8e, 0x02, 0x46, 0xf1, 0x43, 0xa8, 0xfa, 0xf1, 0xd4,
	0x09, 0x63, 0xd7, 0x95, 0xce, 0x6d, 0xab, 0xe2, 0xc7, 0x53, 0x31, 0x91, 0x4b, 0xb3, 0x80, 0x51,
	0x79, 0x75, 0xa9, 0x24, 0x5c, 0xda, 0x1c, 0x5a, 0x9b, 0x39, 0x69, 0x85, 0x0e, 0x80, 0x08, 0x62,
	0x61, 0xc8, 0x83, 0xb0, 0x8d, 0x0e, 0x8a, 0x77, 0x14, 0x59, 0x9b, 0xc0, 0x5d, 0x68, 0x88, 0x74,
	0x96, 0x3b, 0x0a, 0x77, 0x3a, 0x36, 0x66, 0xb4, 0x17, 0xd0, 0x3c, 0x9b, 0xf8, 0xd4, 0x5e, 0xa5,
	0xa8, 0x50, 0xfc, 0xc8, 0xe6, 0xb2, 0x7d, 0xc3, 0x12, 0xc7, 0x8d, 0xa5, 0x0a, 0x1b, 0x4b, 0x69,
	0x06, 0xb4, 0x36, 0xed, 0xff, 0xd5, 0x5c, 0x7b, 0x0c, 0x3b, 0x22, 0x66, 0xb4, 0x6a, 0xf6, 0x77,
	0x0d, 0xed, 0x25, 0xec, 0xde, 0x1a, 0x4a, 0x3f, 0xf6, 0x14, 0xea, 0x6b, 0x2b, 0xfd, 0xe3, 0x0f,
	0x5b, 0x1f, 0x39, 0x3a, 0x81, 0xfa, 0xda, 0x2b, 0xc7, 0x00, 0x65, 0xdd, 0xb4, 0x8c, 0xfe, 0x58,
	0x55, 0x70, 0x0d, 0xb6, 0x2c, 0xe3, 0x55, 0xef, 0xad, 0x8a, 0xf0, 0x36, 0xd4, 0x4e, 0xad, 0xf3,
	0x9e, 0xde, 0xef, 0xd9, 0x63, 0xb5, 0x70, 0xe4, 0x41, 0x7d, 0xed, 0x81, 0xe3, 0x2a, 0x94, 0x46,
	0xe6, 0x70, 0xa0, 0x2a, 0xb8, 0x01, 0xd5, 0x81, 0x31, 0x76, 0x86, 0xe7, 0xba, 0xa1, 0x22, 0xbc,
	0x07, 0xf7, 0x04, 0xb2, 0xdf, 0xf4, 0xfb, 0x4e, 0x6f, 0xa8, 0x3b, 0x23, 0xcb, 0xd0, 0xd5, 0x02,
	0x6e, 0xc1, 0xce, 0x99, 0x39, 0xd4, 0x25, 0x6f, 0xd8, 0xf6, 0xb9, 0x65, 0xab, 0x45, 0xbc, 0x0b,
	0xaa, 0x24, 0xc5, 0x8c, 0x91, 0xd2, 0x6a, 0xe9, 0xf4, 0xf9, 0xe5, 0x82, 0x28, 0x57, 0x0b, 0xa2,
	0x5c, 0x2f, 0x08, 0xfa, 0xbd, 0x20, 0xe8, 0x73, 0x42, 0xd0, 0xb7, 0x84, 0xa0, 0xef, 0x09, 0x41,
	0x3f, 0x12, 0x82, 0x2e, 0x13, 0x82, 0x7e, 0x26, 0x04, 0xfd, 0x4a, 0x88, 0x72, 0x9d, 0x10, 0xf4,
	0x75, 0x49, 0x94, 0xcb, 0x25, 0x51, 0xae, 0x96, 0x44, 0xb9, 0x28, 0xcb, 0xbd, 0x4f, 0xfe, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x13, 0x01, 0x0c, 0xac, 0x5a, 0x04, 0x00, 0x00,
}
